# Remove Vim Esc delay
set -sg escape-time 0

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse support
set -g mouse on

# Focus events
set -g focus-events on

# Set colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# -- KEYBINDINGS
# Change prefix to Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Pane splitting (keep current path)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Vim binds pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim binds pane resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# -- APPEARANCE
# Status bar position
set -g status-position bottom

# Status bar colors
set -g status-style 'bg=#13161d fg=#8b949e'
set -g status-left-length 20
set -g status-right-length 50

# Status bar format
set -g status-left '#[fg=#00e68a,bold] #S #[fg=#30363d]│ '
set -g status-right '#[fg=#30363d]│#[fg=#8b949e] %I:%M %p #[fg=#30363d]│#[fg=#8b949e] %d-%b-%y '

# Window format
setw -g window-status-format ' #I:#W '
setw -g window-status-current-format '#[fg=#00e68a,bold] #I:#W '

# Pane and message colors
set -g pane-border-style 'fg=#30363d'
set -g pane-active-border-style 'fg=#00e68a'
set -g message-style 'bg=#00e68a fg=#000000 bold'

# -- COPY MODE
# Use vim binds
setw -g mode-keys vi

# Vim binds for copy
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
